apiVersion: maas.opendatahub.io/v1alpha1
kind: ExternalModel
metadata:
  name: qwen36-35b-a3b
  namespace: my-first-model
  labels:
    app.kubernetes.io/part-of: wings-demo
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
spec:
  provider: openai
  endpoint: maas-rhdp.apps.maas.redhatworkshops.io
  targetModel: qwen36-35b-a3b
  credentialRef:
    name: wings-maas-upstream-api-key
