apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: gpt-oss-20b
  namespace: my-first-model
  labels:
    app.kubernetes.io/part-of: wings3-demo
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
spec:
  modelRef:
    kind: ExternalModel
    name: gpt-oss-20b
