# MaaS 3.5 requires maas-db-config in redhat-ods-applications.
apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: wings3-demo
type: Opaque
stringData:
  DB_CONNECTION_URL: postgresql://maas:wings3-maas-dev@wings3-maas-postgres.redhat-ods-applications.svc:5432/maas?sslmode=disable
